/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryStatus.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryStatus (1 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryStatus : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *clientId;

#pragma mark -
#pragma mark "statusAPI" methods
// These create a GTLQueryStatus object.

// Method: status.statusAPI.getStatus
//  Authorization scope(s):
//   kGTLAuthScopeStatusUserinfoEmail
// Fetches a GTLStatusStatus.
+ (id)queryForStatusAPIGetStatusWithClientId:(NSString *)clientId;

@end
