/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryStatus.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryStatus (1 custom class methods, 2 custom properties)

#import "GTLQueryStatus.h"

#import "GTLStatusStatus.h"

@implementation GTLQueryStatus

@dynamic clientId, fields;

#pragma mark -
#pragma mark "statusAPI" methods
// These create a GTLQueryStatus object.

+ (id)queryForStatusAPIGetStatusWithClientId:(NSString *)clientId {
  NSString *methodName = @"status.statusAPI.getStatus";
  GTLQueryStatus *query = [self queryWithMethodName:methodName];
  query.clientId = clientId;
  query.expectedObjectClass = [GTLStatusStatus class];
  return query;
}

@end
