/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStatusConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API

#import "GTLStatusConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeStatusUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
