/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStatusStatus.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API
// Classes:
//   GTLStatusStatus (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStatusStatus
//

@interface GTLStatusStatus : GTLObject
@property (copy) NSString *clientId;
@property (copy) NSString *latestVersion;
@property (copy) NSString *message;
@property (copy) NSString *title;
@end
