/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStatus.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API

#import "GTLStatusConstants.h"

#import "GTLStatusStatus.h"

#import "GTLQueryStatus.h"
#import "GTLServiceStatus.h"
