/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStatusStatus.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   status/v1
// Description:
//   This is an API
// Classes:
//   GTLStatusStatus (0 custom class methods, 4 custom properties)

#import "GTLStatusStatus.h"

// ----------------------------------------------------------------------------
//
//   GTLStatusStatus
//

@implementation GTLStatusStatus
@dynamic clientId, latestVersion, message, title;
@end
